# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtDesignerComponents/ComposantTP4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(862, 565)
        self.mLabel = QtWidgets.QLabel(Form)
        self.mLabel.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.mLabel.setStyleSheet("background-color: #00ff00;")
        self.mLabel.setText("")
        self.mLabel.setObjectName("mLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 510, 611, 27))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.mLineEdit.setReadOnly(True)
        self.mLineEdit.setObjectName("mLineEdit")
        self.horizontalLayout.addWidget(self.mLineEdit)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.mButtonBrowse = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.mButtonBrowse.setObjectName("mButtonBrowse")
        self.horizontalLayout.addWidget(self.mButtonBrowse)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(680, 190, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mButtonN = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonN.setObjectName("mButtonN")
        self.verticalLayout.addWidget(self.mButtonN)
        self.mButtonP = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.mButtonP.setObjectName("mButtonP")
        self.verticalLayout.addWidget(self.mButtonP)
        self.timerButton = QtWidgets.QPushButton(Form)
        self.timerButton.setGeometry(QtCore.QRect(710, 340, 89, 25))
        self.timerButton.setCheckable(True)
        self.timerButton.setObjectName("timerButton")

        self.retranslateUi(Form)
        self.mButtonN.clicked.connect(Form.next)
        self.mButtonP.clicked.connect(Form.previous)
        self.mButtonBrowse.clicked.connect(Form.loadFiles)
        self.timerButton.clicked.connect(Form.animate)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mLineEdit.setText(_translate("Form", "Chemin vers l\'image chargée"))
        self.mButtonBrowse.setText(_translate("Form", "..."))
        self.mButtonN.setText(_translate("Form", "Next"))
        self.mButtonP.setText(_translate("Form", "Previous"))
        self.timerButton.setText(_translate("Form", "START"))
